services:

    asa1:
        extends:
            file: common.yml
            service: asa
        container_name: ${COMPOSE_PROJECT_NAME}_asa1
        ports:
            - "${ASA1_SERVER_PORT}:${ASA1_SERVER_PORT}/udp"
        environment:
            - "SERVER_MAP=${ASA1_SERVER_MAP}"
            - "SESSION_NAME=${ASA_SESSION_PREFIX}${ASA1_SESSION_NAME}"
            - "SERVER_PORT=${ASA1_SERVER_PORT}"
            - "DISCORD_WEBHOOK_URL=${ASA1_DISCORD_WEBHOOK_URL:-${ASA_DISCORD_WEBHOOK_URL}}"
            - "LOG_FILE=ShooterGame_asa1.log" # Avoid log file conflicts

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#  asa<no>:
#    extends:
#      file: common.yml
#      service: asa
#    container_name: ${COMPOSE_PROJECT_NAME}_asa<no>
#    ports:
#      - "${ASA<no>_SERVER_PORT}:${ASA<no>_SERVER_PORT}/udp"
#    environment:
#      - "SERVER_MAP=${ASA<no>_SERVER_MAP}"
#      - "SESSION_NAME=${ASA_SESSION_PREFIX}${ASA<no>_SESSION_NAME}"
#      - "SERVER_PORT=${ASA<no>_SERVER_PORT}"
#      - "DISCORD_WEBHOOK_URL=${ASA<no>_DISCORD_WEBHOOK_URL:-${ASA_DISCORD_WEBHOOK_URL}}"
#      - "LOG_FILE=ShooterGame_asa<no>.log" # Avoid log file conflicts
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
